#!/bin/sh /etc/rc.common

USE_PROCD=1
START=19
STOP=90

start_service() {
    local owner=$(cat /etc/cf_node_name 2>/dev/null)
    
    if [ -z "$owner" ]; then
        logger -t "cf-monitor" "Loi: Khong tim thay file /etc/cf_node_name."
        return 1
    fi

    . /lib/functions.sh
    config_load cloudflare_ddns

    local en_ubus en_ddos en_hc
    config_get en_ubus "$owner" enable_ubus '1'
    config_get en_ddos "$owner" enable_ddos '1'
    config_get en_hc "$owner" enable_healthcheck '1'

    # Thuc the 1: Luong lang nghe UBUS
    if [ "$en_ubus" = "1" ]; then
        procd_open_instance "ubus_listener"
        procd_set_param command /usr/bin/monitor.sh "$owner" "ubus"
        procd_set_param respawn
        procd_close_instance
    fi

    # Thuc the 2: Luong giam sat DDOS
    if [ "$en_ddos" = "1" ]; then
        procd_open_instance "ddos_scanner"
        procd_set_param command /usr/bin/monitor.sh "$owner" "ddos"
        procd_set_param respawn
        procd_close_instance
    fi

    # Thuc the 3: Luong giam sat Healthcheck (Decentralized)
    if [ "$en_hc" = "1" ]; then
        procd_open_instance "healthcheck_scanner"
        procd_set_param command /usr/bin/monitor.sh "$owner" "healthcheck"
        procd_set_param respawn
        procd_close_instance
    fi
}